version: '2'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/ssl/:/etc/nginx/ssl/"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/ssl/31FD0EA7CCC91872E2321B4C844EB8F1.txt:/etc/nginx/conf.d/31FD0EA7CCC91872E2321B4C844EB8F1.txt"
    links:
      - express

  express:
    image: node:16.19.0-alpine
    container_name: express
    hostname: express
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"
