server {
    listen 80;
    server_name juju-l.saltapl.com;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://express:3000/;
    }
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}
